#!/bin/sh
### BEGIN INIT INFO
# Provides:          spdyproxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
# Copyright Rene Mayrhofer, Gibraltar, 1999
# This script is distibuted under the GPL

start(){
	nohup /usr/bin/spdyproxy -k /etc/certs/vpn.mawenjian.net.key -c /etc/certs/vpn.mawenjian.net.pem -p 4444 -U mawenjian -P [PASSWORD] >/dev/null 2>/dev/null &
}

stop(){
	lsof -i:4444
	echo "do it yourself!"
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload)
        stop
        start
        ;;
*)
        echo "Usage: $0 {start|reload|stop}"
        exit 1
        ;;
esac
